name: TextConvo
dependencies:
  - python=3.9
  - pip
  - pip:
    - absl-py==0.9.0
    - argon2-cffi==20.1.0
    - arrow==0.13.1
    - asn1crypto==1.2.0
    - astor==0.8.0
    - async-generator==1.10
    - attrs==19.3.0
    - Automat==0.8.0
    - backcall==0.1.0
    - bcrypt==3.1.7
    - beautifulsoup4==4.8.2
    - bleach==3.3.0
    - blinker==1.4
    - cachetools==3.1.1
    - certifi==2019.11.28
    - cffi==1.13.0
    - chardet==3.0.4
    - Click==7.0
    - cloudpickle==1.3.0
    # - conda==4.8.2
    # - conda-package-handling==1.6.0
    - constantly==15.1.0
    - cryptography==2.8
    - cssselect==1.1.0
    - cycler==0.10.0
    - Cython==0.29.17
    - cytoolz==0.10.1
    - dask==2.11.0
    - debugpy==1.3.0
    - decorator==4.4.1y
    - defusedxml==0.7.1
    - eli5==0.10.1
    - entrypoints==0.3
    - fastcache==1.1.0
    - future==0.18.2
    - gast==0.2.2
    - gensim==4.0.1
    - gmpy2==2.0.8
    - google-auth==1.11.2
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.1.8
    - graphviz==0.13.2
    - grpcio==1.27.2
    - h5py==2.8.0
    - hyperlink==19.0.0
    - idna==2.8
    - imageio==2.6.1
    - importlib-metadata==1.5.0
    - incremental==17.5.0
    - ipykernel==6.0.0
    - ipython==7.25.0
    - ipython-genutils==0.2.0
    - jedi==0.16.0
    - Jinja2==2.11.1
    - joblib==0.14.1
    - jsonschema==3.2.0
    - jupyter-client==6.1.12
    - jupyter-core==4.7.1
    - jupyterlab-pygments==0.1.2
    - Keras==2.3.1
    - Keras-Applications==1.0.8
    - Keras-Preprocessing==1.1.0
    - kiwisolver==1.1.0
    - leveldb==0.201
    - lightgbm==2.3.0
    - lxml==4.5.0
    - Mako==1.1.1
    - Markdown==3.1.1
    - MarkupSafe==1.1.1
    - matplotlib==3.1.3
    - matplotlib-inline==0.1.2
    - mistune==0.8.4
    - mkl-fft==1.0.15
    - mkl-random==1.1.0
    - mkl-service==2.3.0
    - more-itertools==8.2.0
    - mpmath==1.1.0
    - nbclient==0.5.3
    - nbconvert==6.1.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - networkx==2.4
    - nltk==3.4.5
    - nose==1.3.7
    - notebook==6.4.0
    - numpy==1.18.1
    - oauthlib==3.1.0
    - olefile==0.46
    - opt-einsum==3.1.0
    - packaging==20.1
    - pandas==1.0.1
    - pandocfilters==1.4.3
    - parsel==1.5.2
    - parso==0.6.1
    - patsy==0.5.1
    - peewee==3.10.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - Pillow==7.0.0
    - pluggy==0.13.1
    - prometheus-client==0.11.0
    - prompt-toolkit==3.0.3
    - protobuf==3.11.4
    - ptyprocess==0.6.0
    - py==1.8.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.7
    - pycosat==0.6.3
    - pycparser==2.19
    - PyDispatcher==2.0.5
    - pyglet==1.5.0
    - Pygments==2.5.2
    - pygpu==0.7.6
    - PyHamcrest==1.9.0
    - PyJWT==1.7.1
    - pyOpenSSL==19.0.0
    - pyparsing==2.4.6
    - pyrsistent==0.18.0
    - PySocks==1.7.1
    - pytest==5.3.5
    - pytest-runner==5.2
    - python-dateutil==2.8.1
    - python-gflags==3.1.2
    - pytz==2019.3
    - PyWavelets==1.1.1
    - PyYAML==5.3
    - pyzmq==22.1.0
    - queuelib==1.5.0
    - requests==2.22.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - ruamel-yaml==0.15.46
    - scapy==2.4.3
    - scikit-image==0.16.2
    - scikit-learn==0.22.1
    - scipy==1.4.1
    - Scrapy==1.6.0
    - seaborn==0.10.0
    - Send2Trash==1.7.1
    - service-identity==18.1.0
    - simplejson==3.17.0
    - singledispatch==3.4.0.3
    - six==1.12.0
    - smart-open==5.1.0
    - soupsieve==1.9.5
    - SQLAlchemy==1.3.13
    - statsmodels==0.11.0
    - sympy==1.5.1
    - tabulate==0.8.6
    - tensorboard==2.1.0
    - tensorflow==2.0.0
    - tensorflow-estimator==2.0.0
    - termcolor==1.1.0
    - terminado==0.10.1
    - testpath==0.5.0
    - Theano==1.0.4
    - toolz==0.10.0
    - torch==1.3.1
    - tornado==6.1
    - tqdm==4.36.1
    - traitlets==4.3.3
    - Twisted==19.10.0
    - urllib3==1.24.2
    - w3lib==1.21.0
    - wcwidth==0.1.8
    - webencodings==0.5.1
    - Werkzeug==0.16.1
    - wrapt==1.11.2
    - wxPython==4.0.4
    - zipp==2.2.0
    - zope.interface==4.7.1
